/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.12.2.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as api_auth from "../api/auth.js";
import type * as api_chats from "../api/chats.js";
import type * as api_friends from "../api/friends.js";
import type * as api_messages from "../api/messages.js";
import type * as api_utils_session from "../api/utils/session.js";
import type * as auth_lucia from "../auth/lucia.js";
import type * as auth_withAuth from "../auth/withAuth.js";
import type * as functions_chats from "../functions/chats.js";
import type * as functions_friends from "../functions/friends.js";
import type * as functions_messages from "../functions/messages.js";
import type * as functions_users from "../functions/users.js";
import type * as http from "../http.js";
import type * as types_response from "../types/response.js";
import type * as types_types from "../types/types.js";
import type * as utils from "../utils.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "api/auth": typeof api_auth;
  "api/chats": typeof api_chats;
  "api/friends": typeof api_friends;
  "api/messages": typeof api_messages;
  "api/utils/session": typeof api_utils_session;
  "auth/lucia": typeof auth_lucia;
  "auth/withAuth": typeof auth_withAuth;
  "functions/chats": typeof functions_chats;
  "functions/friends": typeof functions_friends;
  "functions/messages": typeof functions_messages;
  "functions/users": typeof functions_users;
  http: typeof http;
  "types/response": typeof types_response;
  "types/types": typeof types_types;
  utils: typeof utils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
